// ExportManager.swift — Playlist export to Apple Music, Spotify, YouTube Music.
// Apple Music uses MusicKit directly (on-device, no OAuth needed beyond library access).
// Spotify and YouTube Music go through the backend — full OAuth is a v2 feature.
// Decision: separate manager instead of embedding in MusicController to keep concerns split.
import Foundation
import MusicKit

@MainActor
final class ExportManager: ObservableObject {
    @Published var isExporting = false

    struct ExportResult {
        let destination: String
        let matchedCount: Int
        let totalCount: Int

        var summary: String { "\(matchedCount)/\(totalCount) tracks added to \(destination)" }
    }

    var lastResult: ExportResult?

    // MARK: - Apple Music

    func exportToAppleMusic(tracks: [TrackResponse], playlistName: String) async throws {
        isExporting = true
        defer { isExporting = false }

        let status = await MusicAuthorization.request()
        guard status == .authorized else {
            throw ExportError.unauthorized("Apple Music library access denied — check Settings → Privacy")
        }

        // Create empty playlist first, then add matched tracks one by one.
        // Batch create isn't reliable when track search succeeds partially.
        let playlist = try await MusicLibrary.shared.createPlaylist(
            name: playlistName, description: "Generated by MeloMo"
        )

        var matched = 0
        for track in tracks {
            guard let song = try? await searchAppleMusicCatalog(title: track.title, artist: track.artist) else {
                continue   // Track not on Apple Music — expected, not an error
            }
            try? await MusicLibrary.shared.add(song, to: playlist)
            matched += 1
        }

        lastResult = ExportResult(destination: "Apple Music", matchedCount: matched, totalCount: tracks.count)
    }

    // MARK: - Spotify (via backend)

    func exportToSpotify(tracks: [TrackResponse], playlistName: String,
                         accessToken: String, userId: String) async throws {
        isExporting = true
        defer { isExporting = false }

        let response = try await BackendClient.shared.exportPlaylist(
            tracks: tracks, destination: "spotify",
            authToken: accessToken, playlistName: playlistName, userId: userId
        )
        lastResult = ExportResult(destination: "Spotify",
                                  matchedCount: response.matchedCount,
                                  totalCount: response.totalCount)
    }

    // MARK: - YouTube Music (via backend)

    func exportToYouTubeMusic(tracks: [TrackResponse], playlistName: String,
                               accessToken: String) async throws {
        isExporting = true
        defer { isExporting = false }

        let response = try await BackendClient.shared.exportPlaylist(
            tracks: tracks, destination: "youtube_music",
            authToken: accessToken, playlistName: playlistName
        )
        lastResult = ExportResult(destination: "YouTube Music",
                                  matchedCount: response.matchedCount,
                                  totalCount: response.totalCount)
    }

    // MARK: - Private

    private func searchAppleMusicCatalog(title: String, artist: String) async throws -> Song? {
        var request = MusicCatalogSearchRequest(term: "\(title) \(artist)", types: [Song.self])
        request.limit = 1
        let result = try await request.response()
        return result.songs.first
    }
}

enum ExportError: LocalizedError {
    case unauthorized(String)

    var errorDescription: String? {
        if case .unauthorized(let msg) = self { return msg }
        return "Export failed"
    }
}
